[project]
name = 'objective-c_tuesdays'
version = '0.0.1'
requires-python = '== 3.13.*'
dependencies = [
    'beautifulsoup4 == 4.12.3',
    'html5lib == 1.1',
]

[tool.uv]
dev-dependencies = [
    'black',
    'pip',
]
