#!/bin/bash

# https://github.com/validator/validator

vnu \
    --skip-non-html wwwroot \
    --also-check-css wwwroot

vnu \
    --skip-non-html objective-c_tuesdays/tmp \
    --also-check-css objective-c_tuesdays/tmp

