[package]
name = "maze"
version = "0.1.0"
edition = "2021"

[lib]
name = "maze"
path = "src/lib.rs"

[[bin]]
name = "maze"
path = "src/main.rs"

[dependencies]
getrandom = "0.2.5"
oorandom = "11.1.3"
