[package]
name = "gen"
version = "0.1.0"
authors = ["Don McCaughey <don@donm.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.94"
serde_derive = "1.0.94"
serde_yaml = "0.8.9"
structopt = "0.2.18"
url = "1.7.2"
url_serde = "0.2.0"
